<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQh71iAK\DDD_Symfony_Kernels_DDDKernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQh71iAK/DDD_Symfony_Kernels_DDDKernelDevContainer.php') {
    touch(__DIR__.'/ContainerQh71iAK.legacy');

    return;
}

if (!\class_exists(DDD_Symfony_Kernels_DDDKernelDevContainer::class, false)) {
    \class_alias(\ContainerQh71iAK\DDD_Symfony_Kernels_DDDKernelDevContainer::class, DDD_Symfony_Kernels_DDDKernelDevContainer::class, false);
}

return new \ContainerQh71iAK\DDD_Symfony_Kernels_DDDKernelDevContainer([
    'container.build_hash' => 'Qh71iAK',
    'container.build_id' => '512218f9',
    'container.build_time' => 1777135722,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQh71iAK');
