<?php
declare( strict_types=1 );

namespace App\Domain\Integrations\WordPress\Seo\Repo\InternalDB\WebPages;

use App\Domain\Common\Repo\InternalDB\InternalDBEntity;
use App\Domain\Common\Repo\InternalDB\Models\InternalDBMetaTagModel;
use App\Domain\Integrations\WordPress\Seo\Entities\WebPages\Content\Elements\MetaTags\Tags\WPWebPageTitleMetaTag;
use App\Domain\Integrations\WordPress\Seo\Entities\WebPages\Content\Elements\MetaTags\WPWebPageMetaTag;
use App\Domain\Integrations\WordPress\Seo\Entities\WebPages\Content\Elements\WPWebPageTitle;
use App\Domain\Integrations\WordPress\Seo\Entities\WebPages\Content\WPWebPageContentMetaTags;
use DDD\Domain\Base\Entities\DefaultObject;
use DDD\Domain\Base\Entities\Entity;
use DDD\Domain\Base\Entities\LazyLoad\LazyLoad;
use DDD\Domain\Base\Repo\DB\Attributes\EntityCache;
use DDD\Domain\Base\Repo\DB\Doctrine\DoctrineQueryBuilder;
use DDD\Infrastructure\Cache\Cache;
use DDD\Infrastructure\Exceptions\BadRequestException;
use DDD\Infrastructure\Exceptions\InternalErrorException;
use Doctrine\DBAL\Exception;
use Doctrine\ORM\Mapping\MappingException;
use Psr\Cache\InvalidArgumentException;
use ReflectionException;

/**
 * Class InternalDBWPWebPageMetaTagTitle
 * @method WPWebPageTitleMetaTag find(DoctrineQueryBuilder|string|int $idOrQueryBuilder, bool $useEntityRegistryCache = false, ?InternalDBMetaTagModel &$loadedOrmInstance = null, bool $deferredCaching = false, array $initiatorClasses = [] )
 * @property InternalDBMetaTagModel $ormInstance
 */
#[EntityCache(useExtendedRegistryCache: false, ttl: 300, cacheGroup: Cache::CACHE_GROUP_PHPFILES, cacheScopes: [])]
class InternalDBWPWebPageMetaTagTitle extends InternalDBEntity {
	public const BASE_ENTITY_CLASS = WPWebPageTitleMetaTag::class;
	public const BASE_ORM_MODEL = InternalDBMetaTagModel::class;

    /**
     * @param WPWebPageContentMetaTags $initiatingEntity
     * @param LazyLoad $lazyloadAttributeInstance
     *
     * @return WPWebPageTitleMetaTag|null
     * @throws BadRequestException
     * @throws Exception
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws MappingException
     * @throws ReflectionException
     */
    public function lazyload(
        DefaultObject &$initiatingEntity,
        LazyLoad &$lazyloadAttributeInstance
    ): ?WPWebPageTitleMetaTag {
        return $this->getMetaTagByTypeAndId($initiatingEntity->postId, WPWebPageMetaTag::TAG_TYPE_TITLE, $lazyloadAttributeInstance->useCache);
    }

	/**
	 * Applies update/delete restrictions based on Auth::instance()->getAccount
	 *
	 * @param DoctrineQueryBuilder $queryBuilder
	 *
	 * @return bool
	 * @noinspection PhpMissingParentCallCommonInspection*/
	public static function applyUpdateRightsQuery(DoctrineQueryBuilder &$queryBuilder): bool
	{
		return false;
	}

    /**
     * @param bool $useEntityRegistryCache
     *
     * @return WPWebPageTitleMetaTag|null
     * @throws ReflectionException
     */
	public function mapToEntity( bool $useEntityRegistryCache = false ): ?WPWebPageTitleMetaTag
	{
        /** @var WPWebPageTitleMetaTag $entity */
		$entity = parent::mapToEntity( $useEntityRegistryCache );

        $entity->id = $this->ormInstance->id;
        $entity->postId = $this->ormInstance->post_id;
        $entity->type = $this->ormInstance->type ?? WPWebPageTitle::TAG_TYPE_TITLE;
        $entity->content = $this->ormInstance->content;
        $entity->template = $this->ormInstance->template;
        $entity->autoGenerated = $this->ormInstance->auto_generated;

        $entity->variables = $this->processVariablesFromJson($this->ormInstance->variables);
        $entity->uniqueKey = $this->ormInstance->unique_key;

		return $entity;
	}

    /**
     * @param Entity $entity
     *
     * @return bool
     * @throws ReflectionException
     */
	protected function mapToRepository(Entity &$entity): bool
	{
        /** @var WPWebPageTitleMetaTag $entity */
		parent::mapToRepository($entity);
		$ormInstance = $this->ormInstance;

		if (isset($entity->id)) {
			$ormInstance->id = (int)$entity->id;
		}

		if (isset($entity->postId)) {
			$ormInstance->post_id = (int)$entity->postId;
		}

		$ormInstance->type = $entity->type ?? WPWebPageMetaTag::TAG_TYPE_TITLE;
		$ormInstance->content = $entity->content ?? '';
		$ormInstance->template = $entity->formatTemplate() ?? '';
		$ormInstance->auto_generated = $entity->autoGenerated ?? false;

		if (isset($entity->variables)) {
			$ormInstance->variables = json_encode($entity->variables);
		}

		$ormInstance->unique_key = $entity->uniqueKey();
		$this->ormInstance = $ormInstance;

		return true;
	}

    /**
     * Retrieves a WPWebPageMetaTag entity by its ID.
     *
     * @param int $postId The ID of the post to retrieve.
     * @param string $type The type of the meta tag to retrieve.
     * @param bool $useCache
     * @return WPWebPageTitleMetaTag|null The WPWebPageMetaTag entity.
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws ReflectionException
     * @throws Exception
     * @throws MappingException
     */
	public function getMetaTagByTypeAndId(int $postId, string $type, bool $useCache = false): ?WPWebPageTitleMetaTag
    {
        $queryBuilder = self::createQueryBuilder();
		$queryBuilder
			->select('p')
			->from(InternalDBMetaTagModel::class, 'p')
			->where('p.post_id = :postId')
			->andWhere('p.type = :type')
			->setParameter('postId', $postId)
			->setParameter('type', $type);
        return $this->find($queryBuilder, $useCache);
	}
}