<?php

namespace App\Domain\Integrations\WordPress\Setup\Entities;

use DDD\Domain\Base\Entities\ObjectSet;

/**
 * Represents the setup settings for a WordPress integration.
 * @method mixed getParent()
 */
class WPSetupSetting extends ObjectSet
{
    /** @var bool|null */
    public ?bool $autogeneratedCategoriesNotConfirmed = null;

    /** @var bool|null */
    public ?bool $autogeneratedKeywordsNotConfirmed = null;

    /** @var bool|null */
    public ?bool $rankingcoachCompleted = null;

    /** @var bool|null */
    public ?bool $rankingcoachCompletedAuto = null;

    /**
     * Returns a unique key for the WPSetupSetting entity.
     *
     * @return string The unique key.
     */
    public function uniqueKey(): string
    {
        return parent::uniqueKey();
    }
}