<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ULzK15Service extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator._uLzK15' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._uLzK15'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'responseDto' => ['privates', 'DDD\\Presentation\\Base\\Dtos\\HtmlResponseDto', 'getHtmlResponseDtoService', true],
        ], [
            'responseDto' => 'DDD\\Presentation\\Base\\Dtos\\HtmlResponseDto',
        ]);
    }
}
