<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9bjYnK9Service extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.9bjYnK9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9bjYnK9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'keywordService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPKeywordsService', 'getWPKeywordsServiceService', true],
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\MetaTagsGetRequestDto', 'getMetaTagsGetRequestDtoService', true],
        ], [
            'keywordService' => 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPKeywordsService',
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\MetaTagsGetRequestDto',
        ]);
    }
}
