<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M2RkWhNService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.m2RkWhN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m2RkWhN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'e' => ['privates', '.errored..service_locator.m2RkWhN.Exception', NULL, 'Cannot autowire service ".service_locator.m2RkWhN": it references class "Exception" but no such service exists.'],
        ], [
            'e' => 'Exception',
        ]);
    }
}
