<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcnjuTgService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.FcnjuTg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FcnjuTg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Documentation\\Dtos\\DocumentationOpenApiRequestDto', 'getDocumentationOpenApiRequestDtoService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Documentation\\Dtos\\DocumentationOpenApiRequestDto',
        ]);
    }
}
