<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LsA0gjLService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.lsA0gjL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lsA0gjL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\SocialMetaTagsPostRequestDto', 'getSocialMetaTagsPostRequestDtoService', true],
            'webPageService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPWebPageService', 'getWPWebPageServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\SocialMetaTagsPostRequestDto',
            'webPageService' => 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPWebPageService',
        ]);
    }
}
