<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B90QNXYService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.B90QNXY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B90QNXY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\OnboardingRequestDto', 'getOnboardingRequestDtoService', true],
            'wpRequirementsService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPRequirementsService', 'getWPRequirementsServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\OnboardingRequestDto',
            'wpRequirementsService' => 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPRequirementsService',
        ]);
    }
}
