<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S6b1mR_Service extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.s6b1mR.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s6b1mR.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\KeywordsMetaTagsKeywordRequestDto', 'getKeywordsMetaTagsKeywordRequestDtoService', true],
            'webPageService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPWebPageService', 'getWPWebPageServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\KeywordsMetaTagsKeywordRequestDto',
            'webPageService' => 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPWebPageService',
        ]);
    }
}
