<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AgGSHS9Service extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.agGSHS9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.agGSHS9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesService' => ['services', 'App\\Domain\\Common\\Services\\WPCategoriesService', 'getWPCategoriesServiceService', true],
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\Categories\\WPCategoriesGetRequestDto', 'getWPCategoriesGetRequestDtoService', true],
        ], [
            'categoriesService' => 'App\\Domain\\Common\\Services\\WPCategoriesService',
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\Categories\\WPCategoriesGetRequestDto',
        ]);
    }
}
