<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WMis5JZService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.WMis5JZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WMis5JZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\PluginInformationRequestDto', 'getPluginInformationRequestDtoService', true],
            'wpPluginService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Plugin\\Services\\WPPluginService', 'getWPPluginServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\PluginInformationRequestDto',
            'wpPluginService' => 'App\\Domain\\Integrations\\WordPress\\Plugin\\Services\\WPPluginService',
        ]);
    }
}
