<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QRz1rpzService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.QRz1rpz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QRz1rpz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'wpPluginService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Plugin\\Services\\WPPluginService', 'getWPPluginServiceService', true],
            'wpRequirementsService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPRequirementsService', 'getWPRequirementsServiceService', true],
            'wpSeoOptimiserService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPSeoOptimiserService', 'getWPSeoOptimiserServiceService', true],
        ], [
            'wpPluginService' => 'App\\Domain\\Integrations\\WordPress\\Plugin\\Services\\WPPluginService',
            'wpRequirementsService' => 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPRequirementsService',
            'wpSeoOptimiserService' => 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPSeoOptimiserService',
        ]);
    }
}
