<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_M2RkWhN_ExceptionService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.m2RkWhN.Exception' shared service.
     *
     * @return \Exception
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m2RkWhN": it references class "Exception" but no such service exists.');
    }
}
