<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXKCFBService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.ZXKC_fB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZXKC_fB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\Seo\\SeoAnalysisRequestDto', 'getSeoAnalysisRequestDtoService', true],
            'seoOptimiserService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPSeoOptimiserService', 'getWPSeoOptimiserServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\Seo\\SeoAnalysisRequestDto',
            'seoOptimiserService' => 'App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPSeoOptimiserService',
        ]);
    }
}
