<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4QDw3OiService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.service_locator.4QDw3Oi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4QDw3Oi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\WPFlowStepCompletionRequestDto', 'getWPFlowStepCompletionRequestDtoService', true],
            'wpFlowDataCompletionsService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowDataCompletionsService', 'getWPFlowDataCompletionsServiceService', true],
            'wpFlowStepsService' => ['services', 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowStepsService', 'getWPFlowStepsServiceService', true],
        ], [
            'requestDto' => 'App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\WPFlowStepCompletionRequestDto',
            'wpFlowDataCompletionsService' => 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowDataCompletionsService',
            'wpFlowStepsService' => 'App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowStepsService',
        ]);
    }
}
