<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountsServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Common\Services\AccountsService' shared autowired service.
     *
     * @return \App\Domain\Common\Services\AccountsService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Common\\Services\\AccountsService'] = new \App\Domain\Common\Services\AccountsService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
