<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Infrastructure\Services\AppService' shared autowired service.
     *
     * @return \App\Infrastructure\Services\AppService
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->services['App\\Infrastructure\\Services\\AppService'] = $container->createProxy('AppService_05c3deb', function () use ($container) {
                return \AppService_05c3deb::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        return new \App\Infrastructure\Services\AppService();
    }
}
