<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronCommandConstraintValidatorService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Domain\Common\Entities\Crons\CronCommandConstraintValidator' shared autowired service.
     *
     * @return \DDD\Domain\Common\Entities\Crons\CronCommandConstraintValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['DDD\\Domain\\Common\\Entities\\Crons\\CronCommandConstraintValidator'] = new \DDD\Domain\Common\Entities\Crons\CronCommandConstraintValidator();
    }
}
