<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorePluginServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Common\Services\CorePluginService' shared autowired service.
     *
     * @return \App\Domain\Common\Services\CorePluginService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Common\\Services\\CorePluginService'] = new \App\Domain\Common\Services\CorePluginService();
    }
}
