<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronsList_LazyService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.DDD\Symfony\Commands\Common\Crons\CronsList.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.DDD\\Symfony\\Commands\\Common\\Crons\\CronsList.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:crons:list', [], 'Lists all Cron Jobs', false, function () use ($container): \DDD\Symfony\Commands\Common\Crons\CronsList {
            return ($container->privates['DDD\\Symfony\\Commands\\Common\\Crons\\CronsList'] ?? $container->load('getCronsListService'));
        });
    }
}
