<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronsExecute_LazyService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.DDD\Symfony\Commands\Common\Crons\CronsExecute.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.DDD\\Symfony\\Commands\\Common\\Crons\\CronsExecute.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:crons:execute', [], 'Execute all Cron Jobs due', false, function () use ($container): \DDD\Symfony\Commands\Common\Crons\CronsExecute {
            return ($container->privates['DDD\\Symfony\\Commands\\Common\\Crons\\CronsExecute'] ?? $container->load('getCronsExecuteService'));
        });
    }
}
