<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDoctrineModels_LazyService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.DDD\Symfony\Commands\Base\DoctrineModels\CreateDoctrineModels.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.DDD\\Symfony\\Commands\\Base\\DoctrineModels\\CreateDoctrineModels.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-doctrine-models-for-entities', [], 'Creates Doctrine models based on entities', false, function () use ($container): \DDD\Symfony\Commands\Base\DoctrineModels\CreateDoctrineModels {
            return ($container->privates['DDD\\Symfony\\Commands\\Base\\DoctrineModels\\CreateDoctrineModels'] ?? $container->load('getCreateDoctrineModelsService'));
        });
    }
}
