<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronsListService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Commands\Common\Crons\CronsList' shared autowired service.
     *
     * @return \DDD\Symfony\Commands\Common\Crons\CronsList
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['DDD\\Symfony\\Commands\\Common\\Crons\\CronsList'] = $instance = new \DDD\Symfony\Commands\Common\Crons\CronsList();

        $instance->setName('app:crons:list');
        $instance->setDescription('Lists all Cron Jobs');

        return $instance;
    }
}
