<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronsExecuteService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Commands\Common\Crons\CronsExecute' shared autowired service.
     *
     * @return \DDD\Symfony\Commands\Common\Crons\CronsExecute
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['DDD\\Symfony\\Commands\\Common\\Crons\\CronsExecute'] = $instance = new \DDD\Symfony\Commands\Common\Crons\CronsExecute();

        $instance->setName('app:crons:execute');
        $instance->setDescription('Execute all Cron Jobs due');

        return $instance;
    }
}
