<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDoctrineModelsService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Commands\Base\DoctrineModels\CreateDoctrineModels' shared autowired service.
     *
     * @return \DDD\Symfony\Commands\Base\DoctrineModels\CreateDoctrineModels
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['DDD\\Symfony\\Commands\\Base\\DoctrineModels\\CreateDoctrineModels'] = $instance = new \DDD\Symfony\Commands\Base\DoctrineModels\CreateDoctrineModels();

        $instance->setName('app:generate-doctrine-models-for-entities');
        $instance->setDescription('Creates Doctrine models based on entities');

        return $instance;
    }
}
