<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentationOpenApiRequestDtoService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'App\Presentation\Api\Documentation\Dtos\DocumentationOpenApiRequestDto' shared autowired service.
     *
     * @return \App\Presentation\Api\Documentation\Dtos\DocumentationOpenApiRequestDto
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Presentation\\Api\\Documentation\\Dtos\\DocumentationOpenApiRequestDto'] = new \App\Presentation\Api\Documentation\Dtos\DocumentationOpenApiRequestDto(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
