<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentationControllerService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'DDD\Presentation\Base\Controller\DocumentationController' shared autowired service.
     *
     * @return \DDD\Presentation\Base\Controller\DocumentationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['DDD\\Presentation\\Base\\Controller\\DocumentationController'] = $instance = new \DDD\Presentation\Base\Controller\DocumentationController(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('DDD\\Presentation\\Base\\Controller\\DocumentationController', $container));

        return $instance;
    }
}
