<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitiesServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'DDD\Domain\Base\Services\EntitiesService' shared autowired service.
     *
     * @return \DDD\Domain\Base\Services\EntitiesService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['DDD\\Domain\\Base\\Services\\EntitiesService'] = new \DDD\Domain\Base\Services\EntitiesService();
    }
}
