<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlResponseDtoService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Presentation\Base\Dtos\HtmlResponseDto' shared autowired service.
     *
     * @return \DDD\Presentation\Base\Dtos\HtmlResponseDto
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['DDD\\Presentation\\Base\\Dtos\\HtmlResponseDto'] = new \DDD\Presentation\Base\Dtos\HtmlResponseDto();
    }
}
