<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginTokenAuthenticatorService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Security\Authenticators\LoginTokenAuthenticator' shared autowired service.
     *
     * @return \DDD\Symfony\Security\Authenticators\LoginTokenAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['DDD\\Symfony\\Security\\Authenticators\\LoginTokenAuthenticator'] = new \DDD\Symfony\Security\Authenticators\LoginTokenAuthenticator(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['DDD\\Domain\\Common\\Services\\LoginTokensService'] ?? ($container->services['DDD\\Domain\\Common\\Services\\LoginTokensService'] = new \DDD\Domain\Common\Services\LoginTokensService())));
    }
}
