<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginTokensServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'DDD\Domain\Common\Services\LoginTokensService' shared autowired service.
     *
     * @return \DDD\Domain\Common\Services\LoginTokensService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['DDD\\Domain\\Common\\Services\\LoginTokensService'] = new \DDD\Domain\Common\Services\LoginTokensService();
    }
}
