<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageBusService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'Symfony\Component\Messenger\MessageBus' shared autowired service.
     *
     * @return \Symfony\Component\Messenger\MessageBus
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Symfony\\Component\\Messenger\\MessageBus'] = new \Symfony\Component\Messenger\MessageBus();
    }
}
