<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessCLIMessageService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Commands\Base\Messages\ProcessCLIMessage' shared autowired service.
     *
     * @return \DDD\Symfony\Commands\Base\Messages\ProcessCLIMessage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['DDD\\Symfony\\Commands\\Base\\Messages\\ProcessCLIMessage'] = $instance = new \DDD\Symfony\Commands\Base\Messages\ProcessCLIMessage();

        $instance->setName('app:process-cli-message');
        $instance->setDescription('Processes a Message encoded as CLI parameter and executes the corresponding MessageHandler');

        return $instance;
    }
}
