<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessCLIMessage_LazyService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private '.DDD\Symfony\Commands\Base\Messages\ProcessCLIMessage.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.DDD\\Symfony\\Commands\\Base\\Messages\\ProcessCLIMessage.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:process-cli-message', [], 'Processes a Message encoded as CLI parameter and executes the corresponding MessageHandler', false, function () use ($container): \DDD\Symfony\Commands\Base\Messages\ProcessCLIMessage {
            return ($container->privates['DDD\\Symfony\\Commands\\Base\\Messages\\ProcessCLIMessage'] ?? $container->load('getProcessCLIMessageService'));
        });
    }
}
