<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_LoaderService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'routing.loader' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\Config\Loader\LoaderResolver();

        $b = ($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService());

        $c = new \DDD\Symfony\Loaders\CustomAnnotationClassLoader($b);
        $d = new \Symfony\Component\HttpKernel\Config\FileLocator(($container->services['kernel'] ?? $container->get('kernel', 1)));
        $e = new \Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader($b, 'dev');

        $a->addLoader($c);
        $a->addLoader(new \DDD\Symfony\Loaders\CustomAnnotationDirectoryLoader($d, $c));
        $a->addLoader(new \DDD\Symfony\Loaders\CustomAnnotationFileLoader($d, $c));
        $a->addLoader(new \Symfony\Component\Routing\Loader\XmlFileLoader($d, 'dev'));
        $a->addLoader(new \Symfony\Component\Routing\Loader\YamlFileLoader($d, 'dev'));
        $a->addLoader(new \Symfony\Component\Routing\Loader\PhpFileLoader($d, 'dev'));
        $a->addLoader(new \Symfony\Component\Routing\Loader\GlobFileLoader($d, 'dev'));
        $a->addLoader(new \Symfony\Component\Routing\Loader\DirectoryLoader($d, 'dev'));
        $a->addLoader(new \Symfony\Component\Routing\Loader\ContainerLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'kernel' => ['services', 'kernel', 'getKernelService', true],
        ], [
            'kernel' => 'DDD\\Symfony\\Kernels\\DDDKernel',
        ]), 'dev'));
        $a->addLoader($e);
        $a->addLoader(new \Symfony\Component\Routing\Loader\AnnotationDirectoryLoader($d, $e));
        $a->addLoader(new \Symfony\Component\Routing\Loader\AnnotationFileLoader($d, $e));

        return $container->services['routing.loader'] = new \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader($a, ['utf8' => true], []);
    }
}
