<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'DDD\Presentation\Services\RequestService' shared autowired service.
     *
     * @return \DDD\Presentation\Services\RequestService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['DDD\\Presentation\\Services\\RequestService'] = new \DDD\Presentation\Services\RequestService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['router'] ?? $container->getRouterService()));
    }
}
