<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_DevService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'security.firewall.map.context.dev' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.map.context.dev'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.firewall.authenticator.dev'] ?? $container->load('getSecurity_Firewall_Authenticator_DevService'));
            yield 2 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 3), new \Symfony\Component\Security\Http\Firewall\ExceptionListener(($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.authentication.trust_resolver'] ?? ($container->privates['security.authentication.trust_resolver'] = new \Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver())), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), 'dev', NULL, NULL, ($container->privates['DDD\\Symfony\\Security\\AccessDeniedHandlers\\AccessDeniedHandler'] ?? ($container->privates['DDD\\Symfony\\Security\\AccessDeniedHandlers\\AccessDeniedHandler'] = new \DDD\Symfony\Security\AccessDeniedHandlers\AccessDeniedHandler())), ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')), true), NULL, new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('dev', 'security.user_checker', '.security.request_matcher.Iy.T22O', true, true, 'security.user.provider.concrete.users_in_memory', NULL, NULL, 'DDD\\Symfony\\Security\\AccessDeniedHandlers\\AccessDeniedHandler', NULL, [0 => 'DDD\\Symfony\\Security\\Authenticators\\TokenAuthenticator', 1 => 'DDD\\Symfony\\Security\\Authenticators\\LoginTokenAuthenticator'], NULL));
    }
}
