<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_DevService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.dev' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.authenticator.dev'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([0 => ($container->privates['DDD\\Symfony\\Security\\Authenticators\\TokenAuthenticator'] ?? $container->load('getTokenAuthenticatorService')), 1 => ($container->privates['DDD\\Symfony\\Security\\Authenticators\\LoginTokenAuthenticator'] ?? $container->load('getLoginTokenAuthenticatorService'))], ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.event_dispatcher.dev'] ?? $container->load('getSecurity_EventDispatcher_DevService')), 'dev', ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')), true, true, []));
    }
}
