<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['DDD\\Symfony\\Security\\Authenticators\\TokenAuthenticator'] ?? $container->load('getTokenAuthenticatorService'));
        $b = ($container->privates['DDD\\Symfony\\Security\\Authenticators\\LoginTokenAuthenticator'] ?? $container->load('getLoginTokenAuthenticatorService'));

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.zJyh7qS'] ?? $container->get_ServiceLocator_ZJyh7qSService()), ($container->privates['.service_locator.MdXOxPZ'] ?? $container->load('get_ServiceLocator_MdXOxPZService')), ['dev' => [0 => $a, 1 => $b], 'main' => [0 => $a, 1 => $b]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
