<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeoAnalysisRequestDtoService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'App\Presentation\Api\Client\Integrations\WordPress\Dtos\Seo\SeoAnalysisRequestDto' shared autowired service.
     *
     * @return \App\Presentation\Api\Client\Integrations\WordPress\Dtos\Seo\SeoAnalysisRequestDto
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Dtos\\Seo\\SeoAnalysisRequestDto'] = new \App\Presentation\Api\Client\Integrations\WordPress\Dtos\Seo\SeoAnalysisRequestDto(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
