<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenAuthenticatorService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the private 'DDD\Symfony\Security\Authenticators\TokenAuthenticator' shared autowired service.
     *
     * @return \DDD\Symfony\Security\Authenticators\TokenAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['DDD\\Symfony\\Security\\Authenticators\\TokenAuthenticator'] = new \DDD\Symfony\Security\Authenticators\TokenAuthenticator(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['security.access_map'] ?? $container->load('getSecurity_AccessMapService')));
    }
}
