<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPFlowStepsServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Integrations\WordPress\Setup\Services\WPFlowStepsService' shared autowired service.
     *
     * @return \App\Domain\Integrations\WordPress\Setup\Services\WPFlowStepsService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowStepsService'] = new \App\Domain\Integrations\WordPress\Setup\Services\WPFlowStepsService(($container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowCollectorsService'] ?? ($container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowCollectorsService'] = new \App\Domain\Integrations\WordPress\Setup\Services\WPFlowCollectorsService())), ($container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowDataCompletionsService'] ?? ($container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowDataCompletionsService'] = new \App\Domain\Integrations\WordPress\Setup\Services\WPFlowDataCompletionsService())));
    }
}
