<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPFlowQuestionsServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Integrations\WordPress\Setup\Services\WPFlowQuestionsService' shared autowired service.
     *
     * @return \App\Domain\Integrations\WordPress\Setup\Services\WPFlowQuestionsService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Integrations\\WordPress\\Setup\\Services\\WPFlowQuestionsService'] = new \App\Domain\Integrations\WordPress\Setup\Services\WPFlowQuestionsService();
    }
}
