<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPAdvancedSettingsMetaTagsControllerService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Presentation\Api\Client\Integrations\WordPress\Controller\WPAdvancedSettingsMetaTagsController' shared autowired service.
     *
     * @return \App\Presentation\Api\Client\Integrations\WordPress\Controller\WPAdvancedSettingsMetaTagsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Controller\\WPAdvancedSettingsMetaTagsController'] = $instance = new \App\Presentation\Api\Client\Integrations\WordPress\Controller\WPAdvancedSettingsMetaTagsController(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Controller\\WPAdvancedSettingsMetaTagsController', $container));

        return $instance;
    }
}
