<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPSeoOptimiserServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Integrations\WordPress\Seo\Services\WPSeoOptimiserService' shared autowired service.
     *
     * @return \App\Domain\Integrations\WordPress\Seo\Services\WPSeoOptimiserService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Integrations\\WordPress\\Seo\\Services\\WPSeoOptimiserService'] = new \App\Domain\Integrations\WordPress\Seo\Services\WPSeoOptimiserService();
    }
}
