<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPAccountServiceService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Domain\Integrations\WordPress\Common\Services\WPAccountService' shared autowired service.
     *
     * @return \App\Domain\Integrations\WordPress\Common\Services\WPAccountService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Domain\\Integrations\\WordPress\\Common\\Services\\WPAccountService'] = new \App\Domain\Integrations\WordPress\Common\Services\WPAccountService();
    }
}
