<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPOnboardingControllerService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Presentation\Api\Client\Integrations\WordPress\Controller\WPOnboardingController' shared autowired service.
     *
     * @return \App\Presentation\Api\Client\Integrations\WordPress\Controller\WPOnboardingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Controller\\WPOnboardingController'] = $instance = new \App\Presentation\Api\Client\Integrations\WordPress\Controller\WPOnboardingController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Presentation\\Api\\Client\\Integrations\\WordPress\\Controller\\WPOnboardingController', $container));

        return $instance;
    }
}
