<?php

namespace ContainerQh71iAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWPServiceSyncControllerService extends DDD_Symfony_Kernels_DDDKernelDevContainer
{
    /*
     * Gets the public 'App\Presentation\Api\Public\Integrations\WordPress\Controller\WPServiceSyncController' shared autowired service.
     *
     * @return \App\Presentation\Api\Public\Integrations\WordPress\Controller\WPServiceSyncController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Presentation\\Api\\Public\\Integrations\\WordPress\\Controller\\WPServiceSyncController'] = $instance = new \App\Presentation\Api\Public\Integrations\WordPress\Controller\WPServiceSyncController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Presentation\\Api\\Public\\Integrations\\WordPress\\Controller\\WPServiceSyncController', $container));

        return $instance;
    }
}
